// eslint-disable-next-line import/no-anonymous-default-export
export default {
    CREATE_CAR_SUCCESS: 'CREATE_CAR_SUCCESS',
    DELETE_CAR_SUCCESS: 'DELETE_CAR_SUCCESS',
    GET_CARS_SUCCESS: 'GET_CARS_SUCCESS',
    CREATE_TRUCK_SUCCESS: 'CREATE_TRUCK_SUCCESS',
    DELETE_TRUCK_SUCCESS: 'DELETE_TRUCK_SUCCESS',
    GET_TRUCKS_SUCCESS: 'GET_TRUCKS_SUCCESS',
};
