// eslint-disable-next-line import/no-anonymous-default-export
export default {
    UPDATE_USER: 'UPDATE_USER',
    LOAD_USER: 'LOAD_USER',
    LOAD_WIDGETS: 'LOAD_WIDGETS',
    UPDATE_USER_PREFS_HIDDEN_WIDGETS_ADD:
        'UPDATE_USER_PREFS_HIDDEN_WIDGETS_ADD',
    UPDATE_USER_PREFS_HIDDEN_WIDGETS_REMOVE:
        'UPDATE_USER_PREFS_HIDDEN_WIDGETS_REMOVE',
    UPDATE_USER_PREFS_FAVORITE_WIDGETS: 'UPDATE_USER_PREFS_FAVORITE_WIDGETS',
};
